import { useEffect, useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || ''
const demos = [['riya@technorizen.com', 'Riya Kapoor', 'Employee'], ['arjun@technorizen.com', 'Arjun Sharma', 'Developer'], ['neha@technorizen.com', 'Neha Singh', 'Finance'], ['admin@technorizen.com', 'Admin User', 'Administrator']]
const labels = { dashboard: 'Security posture', identity: 'Identity & MFA', resources: 'Resource access', device: 'Device trust & posture', sessions: 'Active sessions', events: 'Security events', audit: 'Audit logs', testing: 'Executable testing', architecture: 'Reference architecture', research: 'Research study', admin: 'Administrator dashboard', users: 'User management', policies: 'Policy management' }

function App() {
  const [token, setToken] = useState(localStorage.getItem('zta_token')), [user, setUser] = useState(null)
  const [login, setLogin] = useState({ email: 'riya@technorizen.com', password: 'Demo@123', otp: '123456' }), [message, setMessage] = useState('')
  const [page, setPage] = useState('dashboard'), [selectedDevice, setSelectedDevice] = useState('dev-trusted-laptop'), [decision, setDecision] = useState(null), [loading, setLoading] = useState(false)
  const [data, setData] = useState({ resources: [], devices: [], sessions: [], logs: [], events: [], policies: [], users: [], stats: null })
  async function api(path, options = {}) { const r = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const body = await r.json(); if (!r.ok) throw Error(body.detail || 'Request failed'); return body }
  async function signIn(e) { e.preventDefault(); setLoading(true); setMessage(''); try { const r = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...login, device_id: selectedDevice }) }); const body = await r.json(); if (!r.ok) throw Error(body.detail || 'Authentication failed'); if (body.mfa_required) { setMessage(`${body.message} Demonstration-only MFA.`); return } localStorage.setItem('zta_token', body.access_token); setToken(body.access_token); setUser(body.user); const devices = { 'riya@technorizen.com': 'dev-riya-trusted', 'arjun@technorizen.com': 'dev-arjun-trusted', 'neha@technorizen.com': 'dev-neha-trusted', 'admin@technorizen.com': 'dev-admin-01' }; setSelectedDevice(devices[login.email] || selectedDevice) } catch (e) { setMessage(e.message) } finally { setLoading(false) } }
  async function refresh(me = user) { if (!token) return; const [resources, devices, sessions] = await Promise.all([api('/resources'), api('/devices'), api('/sessions')]); const next = { resources, devices, sessions, logs: [], events: [], policies: [], users: [], stats: null }; if (['admin', 'analyst'].includes(me?.role)) { next.logs = await api('/audit-logs'); next.events = await api('/events') } if (me?.role === 'admin') { next.stats = await api('/admin/stats'); next.policies = await api('/policies'); next.users = await api('/admin/users') } setData(next) }
  async function evaluate(resource) { setLoading(true); try { setDecision(await api('/access/evaluate', { method: 'POST', body: JSON.stringify({ resource, device_id: selectedDevice, ip: selectedDevice === 'dev-high-risk' ? '203.0.113.55' : undefined }) })); await refresh() } catch (e) { setMessage(e.message) } finally { setLoading(false) } }
  async function posture(profile) { try { await api(`/devices/${selectedDevice}/posture`, { method: 'PUT', body: JSON.stringify(profile) }); await refresh(); setMessage('Device posture persisted. Re-evaluate a resource to inspect the changed decision.') } catch (e) { setMessage(e.message) } }
  async function terminate(id) { try { await api(`/sessions/${id}/terminate`, { method: 'POST' }); await refresh() } catch (e) { setMessage(e.message) } }
  useEffect(() => { if (token) api('/me').then(me => { setUser(me); refresh(me) }).catch(() => { localStorage.removeItem('zta_token'); setToken(null) }) }, [token])
  if (!token || !user) return <Login login={login} setLogin={setLogin} submit={signIn} message={message} loading={loading} />
  const admin = user.role === 'admin', nav = [['dashboard', 'Overview'], ['identity', 'Identity & MFA'], ['resources', 'Resource Access'], ['device', 'Device Trust'], ['sessions', 'Active Sessions'], ['events', 'Security Events'], ['audit', 'Audit Logs'], ['testing', 'Testing'], ['architecture', 'Architecture'], ['research', 'Research']]
    return <div className="app-shell"><aside className="sidebar"><div className="logo"><b>TECHNORIZEN</b><small>ZERO TRUST PORTAL</small></div><div className="live">• ENFORCEMENT LIVE</div><nav>{nav.map(([id, text]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}>{text}</button>)}{admin && <><div className="nav-label">ADMINISTRATION</div>{[['admin', 'Dashboard'], ['users', 'Users'], ['policies', 'Policies']].map(([id, text]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}>{text}</button>)}</>}</nav><div className="account"><b>{user.name}</b><span>{user.role} · MFA verified</span><button onClick={async () => { try { await api('/auth/logout') } catch {} localStorage.removeItem('zta_token'); setToken(null) }}>Sign out</button></div></aside><main className="content"><header><div><span className="eyebrow">TECHNORIZEN SOFTWARE SOLUTIONS / {user.role.toUpperCase()}</span><h1>{labels[page]}</h1></div><span className="badge">Research Prototype / Academic Proof of Concept</span></header>{message && <div className="notice">{message}</div>}{page === 'dashboard' || page === 'admin' ? <Dashboard user={user} stats={data.stats} go={setPage} /> : page === 'identity' ? <Identity user={user} /> : page === 'resources' ? <Resources data={data} selected={selectedDevice} setSelected={setSelectedDevice} evaluate={evaluate} decision={decision} loading={loading} /> : page === 'device' ? <Device data={data} selected={selectedDevice} setSelected={setSelectedDevice} posture={posture} /> : page === 'sessions' ? <Sessions rows={data.sessions} terminate={terminate} /> : page === 'events' ? <Table title="Security events" headers={['Timestamp', 'Type', 'Severity', 'Details']} rows={data.events.map(x => [new Date(x.timestamp).toLocaleString(), x.event_type, x.severity, x.details])} /> : page === 'audit' ? <Table title="Persisted audit log" headers={['Timestamp', 'Action', 'Resource', 'Risk', 'Decision', 'Reason']} rows={data.logs.map(x => [new Date(x.timestamp).toLocaleString(), x.action, x.resource, `${x.risk_level} · ${x.risk_score}`, x.decision, x.reason])} /> : page === 'users' ? <Table title="Technorizen users" headers={['Name', 'Email', 'Role', 'Department', 'MFA', 'Status']} rows={data.users.map(x => [x.name, x.email, x.role, x.department, x.mfa_enabled ? 'Enabled' : 'Disabled', x.locked_until ? 'Locked' : 'Active'])} /> : page === 'policies' ? <Table title="Enforced policies" headers={['Policy', 'Description', 'Role', 'Resource', 'Trust', 'Risk']} rows={data.policies.map(x => [x.name, x.description, x.role, x.resource, x.min_device_trust, x.max_risk])} /> : page === 'architecture' ? <Architecture /> : page === 'research' ? <Research /> : <Testing evaluate={evaluate} decision={decision} />}</main></div>
}

function Login({ login, setLogin, submit, message, loading }) { return <div className="login"><div className="login-art"><span className="eyebrow">NEVER TRUST, ALWAYS VERIFY</span><h1>Trust is a<br /><i>continuous</i><br />decision.</h1><p>Identity, device posture, risk, and policy evaluated at every request.</p></div><form className="login-card" onSubmit={submit}><div className="logo dark"><b>TECHNORIZEN SOFTWARE SOLUTIONS</b><small>ZERO TRUST SECURITY PORTAL</small></div><span className="eyebrow">SECURE ACCESS</span><h2>Sign in</h2><label>Corporate Email<input type="email" required value={login.email} onChange={e => setLogin({ ...login, email: e.target.value })} /></label><label>Password<input type="password" required value={login.password} onChange={e => setLogin({ ...login, password: e.target.value })} /></label><label>Demo MFA code<input inputMode="numeric" value={login.otp} onChange={e => setLogin({ ...login, otp: e.target.value })} /></label><p className="helper">Demo MFA - Research Prototype<br />Demo OTP: <b>123456</b>. Demonstration-only, not production MFA.</p>{message && <div className="notice">{message}</div>}<button className="primary" disabled={loading}>{loading ? 'Verifying...' : 'Sign In'}</button><small className="protected">Protected by Zero Trust Security</small><div className="demo-list">{demos.map(([email, name, role]) => <button type="button" key={email} onClick={() => setLogin({ email, password: 'Demo@123', otp: '123456' })}>{name} · {role}</button>)}</div></form></div> }
function Dashboard({ user, stats, go }) { return <><section className="hero"><div><span className="eyebrow">ZERO TRUST CONTROL PLANE</span><h2>Never trust.<br /><em>Always verify.</em></h2><p>Every request is checked against {user.name}'s identity, MFA, device posture, role, resource sensitivity, and risk.</p><button className="primary" onClick={() => go('resources')}>Request a protected resource</button></div><div className="hero-score"><strong>{stats?.trusted_devices ?? '—'}</strong><span>trusted devices</span></div></section><div className="metrics">{[['Active Users', stats?.active_users ?? '—'], ['Active Sessions', stats?.active_sessions ?? '—'], ['High Risk Sessions', stats?.high_risk ?? '—'], ['Blocked Requests', stats?.denied ?? '—']].map(([x, y]) => <article key={x}><span>{x}</span><strong>{y}</strong><small>live backend telemetry</small></article>)}</div><section className="panel pipeline"><span className="eyebrow">ENFORCEMENT PIPELINE</span><div>{['Password', 'MFA', 'Identity', 'Device', 'Risk', 'Policy', 'Resource', 'Audit'].map(x => <span key={x}>{x}</span>)}</div></section></> }
function Identity({ user }) { return <section className="grid-two"><article className="panel"><span className="eyebrow">VERIFIED PRINCIPAL</span><h2>{user.name}</h2><dl><dt>Email</dt><dd>{user.email}</dd><dt>Role</dt><dd>{user.role}</dd><dt>Department</dt><dd>{user.department}</dd></dl></article><article className="panel trust"><span className="eyebrow">IDENTITY TRUST SCORE</span><strong>100<span>/100</span></strong><b className="success">✓ VERIFIED</b>{['Valid credentials', 'MFA verified', 'Active account', 'Valid session', 'Normal authentication pattern'].map(x => <p key={x}>✓ {x}</p>)}</article></section> }
function Resources({ data, selected, setSelected, evaluate, decision, loading }) { return <><section className="toolbar"><div><span className="eyebrow">POLICY ENFORCEMENT POINT</span><p>Requests are sent to the backend policy engine. The frontend cannot grant access.</p></div><select value={selected} onChange={e => setSelected(e.target.value)}>{data.devices.map(x => <option key={x.id} value={x.id}>{x.id} · trust {x.trust_score}</option>)}</select></section><div className="resource-grid"><div>{data.resources.map(x => <article className="resource" key={x.id}><span className="classification">{x.sensitivity}</span><h3>{x.label}</h3><p>{x.description}</p><small>Required role: {x.required_role}<br />Minimum trust: {x.min_trust} · MFA required</small><button onClick={() => evaluate(x.id)}>Request Access</button></article>)}</div><Decision decision={decision} loading={loading} /></div></> }
function Decision({ decision, loading }) { if (loading) return <article className="decision empty">Evaluating identity → device → risk → policy...</article>; if (!decision) return <article className="decision empty">Select a resource to inspect a live policy decision.</article>; const deny = decision.decision === 'DENY', step = decision.decision.includes('STEP'); return <article className={`decision ${deny ? 'danger' : step ? 'warning' : 'success-panel'}`}><span className="eyebrow">ZERO TRUST POLICY DECISION</span><h2>{decision.decision.replaceAll('_', ' ')}</h2><div className="decision-score"><strong>{decision.risk.score}</strong><span>/100 RISK · {decision.risk.level}<br />Device trust: {decision.device_trust}/100</span></div><h4>Policy checks</h4>{[['Identity', true], ['MFA', true], ['Role / Policy', !decision.policy.includes('default')], ['Device', decision.device_trust >= 50], ['Risk', decision.risk.score <= 60], ['Resource Policy', !decision.policy.includes('default')]].map(([x, pass]) => <p className="check" key={x}><span className={pass ? 'success' : 'failure'}>{pass ? 'PASS' : 'FAIL'}</span>{x}</p>)}<h4>Reason</h4><p>{decision.reasons.join('; ')}</p></article> }
function Device({ data, selected, setSelected, posture }) { const profiles = [['Trusted Laptop', { managed: true, encrypted: true, edr_active: true, status: 'trusted', trust_score: 95 }], ['Unmanaged Laptop', { managed: false, encrypted: true, edr_active: true, status: 'untrusted', trust_score: 55 }], ['High-Risk Device', { managed: false, encrypted: false, edr_active: false, status: 'untrusted', trust_score: 15 }]]; return <section className="panel"><span className="eyebrow">SIMULATED RESEARCH-PROTOTYPE DEVICE POSTURE</span><h2>Device trust signals</h2><p>Controlled demo signals. The browser is not inspecting OS, EDR, disk encryption, or real IP reputation.</p><select value={selected} onChange={e => setSelected(e.target.value)}>{data.devices.map(x => <option key={x.id} value={x.id}>{x.id}</option>)}</select><div className="posture-grid">{profiles.map(([name, profile]) => <button key={name} onClick={() => posture(profile)}><b>{name}</b><span>{profile.managed ? 'Managed' : 'Unmanaged'} · {profile.encrypted ? 'Encrypted' : 'No encryption'} · {profile.edr_active ? 'EDR active' : 'EDR inactive'}</span></button>)}</div>{data.devices.filter(x => x.id === selected).map(x => <div className="score-line" key={x.id}><strong>{x.trust_score}/100</strong><span>Device Trust Score · {x.ip}</span></div>)}</section> }
function Sessions({ rows, terminate }) { return <Table title="Session status" headers={['Device', 'Browser', 'MFA', 'Trust', 'Status', 'Action']} rows={rows.map(x => [x.device_id, `${x.os} / ${x.browser}`, x.mfa_verified ? 'Verified' : 'Required', x.trust_score ?? '—', x.revoked ? 'Revoked' : 'Active', <button onClick={() => terminate(x.id)} disabled={x.revoked}>Terminate Session</button>])} /> }
function Table({ title, headers, rows }) { return <section className="panel table-panel"><span className="eyebrow">BACKEND DATA</span><h2>{title}</h2><div className="table"><div className="tr th">{headers.map(x => <span key={x}>{x}</span>)}</div>{rows.length ? rows.map((row, i) => <div className="tr" key={i}>{row.map((cell, j) => <span key={j}>{cell}</span>)}</div>) : <p>No records available for this identity.</p>}</div></section> }
function Architecture() { return <section className="panel architecture"><span className="eyebrow">NIST-ALIGNED CONCEPTUAL MODEL</span><h2>Never trust, always verify</h2><div className="flow">{['USER', 'IDENTITY PROVIDER', 'PASSWORD + MFA', 'DEVICE POSTURE', 'RISK ENGINE', 'POLICY DECISION POINT', 'POLICY ENFORCEMENT POINT', 'RESOURCE', 'AUDIT / MONITORING'].map(x => <span key={x}>{x}</span>)}</div><p>Identity, MFA, device trust, risk, policy, resource protection, monitoring, and audit logging are server-backed prototype controls.</p></section> }
function Research() { return <section className="research"><span className="eyebrow">RESEARCH-BASED STUDY FOR ENTERPRISE SECURITY</span><h2>Implementation of Zero Trust Architecture</h2>{[['Objective', 'Demonstrate continuous, identity-centric authorization for enterprise resources.'], ['Methodology', 'Authenticate, verify MFA, assess posture, calculate risk, evaluate least-privilege policy, and persist evidence.'], ['Risk model', 'Base risk 10 with posture, IP reputation, session, and resource sensitivity factors clamped to 0-100.'], ['Limitations', 'Device posture, EDR status, and IP reputation are simulated. This is not a production endpoint security system and does not replace IAM, SIEM, EDR, MDM, or network security infrastructure.'], ['Future work', 'Real TOTP, endpoint attestation, PostgreSQL, SIEM integration, and network-level micro-segmentation.']].map(([h, p]) => <article key={h}><h3>{h}</h3><p>{p}</p></article>)}</section> }
function Testing({ evaluate, decision }) { const cases = [['ZT-TC-001', 'Legitimate Employee', 'internal-directory', 'ALLOW'], ['ZT-TC-002', 'Employee unauthorized resource', 'financial-reports', 'DENY'], ['ZT-TC-003', 'High-risk device', 'financial-reports', 'DENY'], ['ZT-TC-004', 'Medium risk finance', 'financial-reports', 'STEP-UP MFA'], ['ZT-TC-005', 'Continuous authorization', 'internal-directory', 'ACCESS REVOKED']]; return <section className="panel"><span className="eyebrow">LIVE POLICY ENGINE SCENARIOS</span><h2>Testing methodology</h2>{cases.map(([id, name, resource, expected]) => <div className="test-row" key={id}><b>{id}</b><span>{name}<small>{resource} · expected {expected}</small></span><button onClick={() => evaluate(resource)}>Run</button><strong>{decision?.decision || 'Not run'}</strong></div>)}</section> }

export default App
