import { useEffect, useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || ''
const resources = [
  { id: 'internal-directory', label: 'Employee Directory', sensitivity: 'INTERNAL', description: 'People, teams and reporting lines' },
  { id: 'financial-reports', label: 'Financial Reports', sensitivity: 'RESTRICTED', description: 'Quarterly performance and forecasts' },
  { id: 'security-reports', label: 'Security Reports', sensitivity: 'CONFIDENTIAL', description: 'Incident analysis and controls' },
  { id: 'confidential-documents', label: 'Confidential Documents', sensitivity: 'CONFIDENTIAL', description: 'Strategy and legal material' },
]

function App() {
  const [token, setToken] = useState(localStorage.getItem('zta_token'))
  const [user, setUser] = useState(null)
  const [login, setLogin] = useState({ email: 'employee@acme.test', password: 'Demo@123', otp: '123456' })
  const [loginMessage, setLoginMessage] = useState('')
  const [active, setActive] = useState('overview')
  const [stats, setStats] = useState(null)
  const [logs, setLogs] = useState([])
  const [decision, setDecision] = useState(null)
  const [selectedDevice, setSelectedDevice] = useState('dev-trusted-01')
  const [loading, setLoading] = useState(false)
  async function api(path, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Request failed'); return data }
  async function signIn(event) { event.preventDefault(); setLoading(true); setLoginMessage(''); try { const data = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...login, device_id: 'dev-trusted-01' }) }).then((response) => response.json()); if (data.mfa_required) { setLoginMessage(data.message); return } localStorage.setItem('zta_token', data.access_token); setToken(data.access_token); setUser(data.user) } catch (error) { setLoginMessage(error.message) } finally { setLoading(false) } }
  async function loadData(currentUser = user) { if (!token) return; if (!['admin', 'analyst'].includes(currentUser?.role)) { setStats(null); setLogs([]); return } try { setStats(await api('/dashboard/stats')); setLogs(await api('/audit-logs')) } catch { setStats(null); setLogs([]) } }
  async function evaluate(resource) { setLoading(true); try { setDecision(await api('/access/evaluate', { method: 'POST', body: JSON.stringify({ resource, device_id: selectedDevice, ip: selectedDevice === 'dev-unmanaged-01' ? '203.0.113.44' : undefined }) })); await loadData() } catch (error) { setDecision({ decision: 'ERROR', reasons: [error.message] }) } finally { setLoading(false) } }
  useEffect(() => { if (token) { api('/me').then((currentUser) => { setUser(currentUser); loadData(currentUser) }).catch(() => { localStorage.removeItem('zta_token'); setToken(null) }) } }, [token])
  if (!token || !user) return <Login login={login} setLogin={setLogin} onSubmit={signIn} message={loginMessage} loading={loading} />
  const isSecurity = ['admin', 'analyst'].includes(user.role)
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">ZT</span><span><b>Sentinel</b><small>zero trust console</small></span></div><div className="scope"><span className="live-dot" /> ENFORCEMENT LIVE</div><nav><button className={active === 'overview' ? 'nav-active' : ''} onClick={() => setActive('overview')}><span>◈</span> Overview</button><button className={active === 'resources' ? 'nav-active' : ''} onClick={() => setActive('resources')}><span>▣</span> Resource access</button>{isSecurity && <button className={active === 'events' ? 'nav-active' : ''} onClick={() => setActive('events')}><span>⌁</span> Security events <em>{stats?.high_risk || 0}</em></button>}<button className={active === 'research' ? 'nav-active' : ''} onClick={() => setActive('research')}><span>≡</span> Research notes</button></nav><div className="sidebar-footer"><div className="avatar">{user.name?.split(' ').map((part) => part[0]).join('')}</div><div><b>{user.name}</b><small>{user.role} · MFA verified</small></div><button className="icon-button" title="Sign out" onClick={() => { localStorage.removeItem('zta_token'); setToken(null) }}>↗</button></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">ENTERPRISE SECURITY / {user.role.toUpperCase()}</p><h1>{active === 'overview' ? 'Security posture' : active === 'resources' ? 'Continuous authorization' : active === 'events' ? 'Security events' : 'Research notes'}</h1></div><div className="top-status"><span className="pulse" /> Policy engine healthy <span className="top-date">06 SEP 2026 · 14:32 UTC</span></div></header>{active === 'overview' && <Overview stats={stats} user={user} onExplore={() => setActive('resources')} />}{active === 'resources' && <Resources selectedDevice={selectedDevice} setSelectedDevice={setSelectedDevice} evaluate={evaluate} decision={decision} loading={loading} />}{active === 'events' && <Events logs={logs} />}{active === 'research' && <Research />}</main></div>
}

function Login({ login, setLogin, onSubmit, message, loading }) { return <div className="login-page"><div className="login-visual"><div className="visual-grid" /><span className="orbit orbit-one" /><span className="orbit orbit-two" /><div className="visual-copy"><p className="eyebrow">SENTINEL / ZTA-01</p><h1>Trust is a<br /><i>continuous</i><br />decision.</h1><p>Identity, device and context evaluated at every request.</p></div><div className="principles"><span>01 / VERIFY IDENTITY</span><span>02 / ASSESS DEVICE</span><span>03 / ENFORCE POLICY</span></div></div><div className="login-panel"><div className="brand dark"><span className="brand-mark">ZT</span><span><b>Sentinel</b><small>zero trust console</small></span></div><div className="login-form"><p className="eyebrow">SECURE ACCESS PORTAL</p><h2>Sign in to the<br /><span>security console</span></h2><p className="muted">Use a demo identity to explore the enforcement pipeline.</p><form onSubmit={onSubmit}><label>Identity<input type="email" value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })} /></label><label>Passphrase<input type="password" value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })} /></label><label>Authenticator code <small>DEMO: 123456</small><input inputMode="numeric" placeholder="Required after first step" value={login.otp} onChange={(e) => setLogin({ ...login, otp: e.target.value })} /></label>{message && <div className="notice">{message}</div>}<button className="primary full" disabled={loading}>{loading ? 'Verifying...' : 'Verify identity  →'}</button></form><div className="demo-users"><span>DEMO IDENTITIES</span><button onClick={() => setLogin({ email: 'employee@acme.test', password: 'Demo@123', otp: '123456' })}>Employee</button><button onClick={() => setLogin({ email: 'admin@acme.test', password: 'Demo@123', otp: '123456' })}>Admin</button><button onClick={() => setLogin({ email: 'analyst@acme.test', password: 'Demo@123', otp: '123456' })}>Analyst</button></div></div></div></div> }

function Overview({ stats, user, onExplore }) { const cards = [{ label: 'Access requests', value: stats?.total_requests || 0, tone: 'blue' }, { label: 'Allowed', value: stats?.allowed || 0, tone: 'green' }, { label: 'Denied / challenged', value: stats?.denied || 0, tone: 'red' }, { label: 'High-risk events', value: stats?.high_risk || 0, tone: 'amber' }]; return <><section className="hero-banner"><div><p className="eyebrow cyan">LIVE CONTROL PLANE</p><h2>Every request tells<br />a story about trust.</h2><p>Sentinel continuously evaluates {user.role} access against identity, device posture, policy and risk.</p><button className="primary" onClick={onExplore}>Run an access evaluation <span>↗</span></button></div><div className="trust-ring"><div className="ring-inner"><strong>{stats?.trusted_devices || 2}</strong><small>trusted devices</small></div></div></section><section className="metric-grid">{cards.map((card) => <div className="metric" key={card.label}><span className={`metric-dot ${card.tone}`} /><p>{card.label}</p><strong>{card.value.toString().padStart(2, '0')}</strong><small>live telemetry</small></div>)}</section><section className="lower-grid"><div className="panel posture"><div className="panel-heading"><div><p className="eyebrow">DECISION DISTRIBUTION</p><h3>Policy outcomes</h3></div><span className="tag">LAST 24H</span></div><div className="bars"><div className="bar-row"><span>Allowed</span><div><i className="bar green" style={{ width: `${Math.max(8, (stats?.allowed || 0) * 35)}%` }} /></div><b>{stats?.allowed || 0}</b></div><div className="bar-row"><span>Denied</span><div><i className="bar red" style={{ width: `${Math.max(8, (stats?.denied || 0) * 35)}%` }} /></div><b>{stats?.denied || 0}</b></div><div className="bar-row"><span>Step-up</span><div><i className="bar amber" style={{ width: '18%' }} /></div><b>01</b></div></div><div className="chart-footer"><span><i className="legend green" />ALLOW</span><span><i className="legend red" />DENY</span><span><i className="legend amber" />STEP-UP</span></div></div><div className="panel principle-panel"><p className="eyebrow">RESEARCH LENS</p><h3>Never trust.<br /><em>Always verify.</em></h3><p>Authentication opens a session. Authorization is recomputed for every sensitive resource request.</p><button className="text-button" onClick={onExplore}>Inspect the pipeline <span>→</span></button></div></section></> }

function Resources({ selectedDevice, setSelectedDevice, evaluate, decision, loading }) { return <><section className="control-strip"><div><p className="eyebrow">POLICY ENFORCEMENT POINT</p><h2>Test the trust boundary</h2><p>Choose a device posture, then request a resource. The backend evaluates every signal.</p></div><label className="device-select">Simulated device<select value={selectedDevice} onChange={(e) => setSelectedDevice(e.target.value)}><option value="dev-trusted-01">Managed / encrypted / EDR active</option><option value="dev-unmanaged-01">Unmanaged / suspicious IP</option></select></label></section><div className="resource-layout"><div className="resource-list">{resources.map((resource) => <button className="resource-row" key={resource.id} onClick={() => evaluate(resource.id)}><span className="resource-icon">{resource.sensitivity === 'RESTRICTED' ? '◆' : '◇'}</span><span><b>{resource.label}</b><small>{resource.description}</small></span><span className={`sensitivity ${resource.sensitivity.toLowerCase()}`}>{resource.sensitivity}</span><span className="arrow">→</span></button>)}</div><Decision decision={decision} loading={loading} /></div></> }

function Decision({ decision, loading }) { if (loading) return <div className="decision-panel empty"><span className="spinner" /><h3>Evaluating signals...</h3><p>Identity → device → risk → policy</p></div>; if (!decision) return <div className="decision-panel empty"><div className="empty-mark">◎</div><h3>Awaiting a request</h3><p>Select a resource to see an explainable decision from the live policy engine.</p></div>; const tone = decision.decision === 'ALLOW' ? 'allow' : decision.decision === 'DENY' ? 'deny' : 'step'; return <div className={`decision-panel ${tone}`}><div className="decision-top"><span className="decision-icon">{tone === 'allow' ? '✓' : tone === 'deny' ? '×' : '!'}</span><div><p className="eyebrow">POLICY DECISION</p><h2>{decision.decision.replaceAll('_', ' ')}</h2></div></div><div className="score"><div><span>RISK SCORE</span><strong>{decision.risk?.score || 0}</strong><small>/ 100 · {decision.risk?.level}</small></div><div className="score-track"><i style={{ width: `${decision.risk?.score || 0}%` }} /></div></div><div className="decision-meta"><span>DEVICE TRUST <b>{decision.device_trust}/100</b></span><span>POLICY <b>{decision.policy}</b></span></div><div className="reasons"><p className="eyebrow">SIGNALS OBSERVED</p>{decision.reasons?.map((reason) => <span key={reason}>+ {reason}</span>)}</div></div> }

function Events({ logs }) { return <div className="panel events-panel"><div className="panel-heading"><div><p className="eyebrow">CENTRALIZED AUDIT LOG</p><h3>Recent enforcement events</h3></div><span className="tag">{logs.length} EVENTS</span></div><div className="event-table"><div className="event-head"><span>DECISION</span><span>RESOURCE</span><span>RISK</span><span>TIME</span></div>{logs.length ? logs.map((log) => <div className="event-row" key={log.id}><span className={`event-pill ${log.decision.toLowerCase().split('_')[0]}`}>{log.decision.replace('_AUTHENTICATION', '')}</span><span>{log.resource}</span><span className={`risk-${log.risk_level.toLowerCase()}`}>{log.risk_level} · {log.risk_score}</span><span>{new Date(log.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>) : <p className="empty-table">No events yet. Run an access evaluation first.</p>}</div></div> }

function Research() { return <div className="research-grid"><div className="research-hero"><p className="eyebrow cyan">RESEARCH NOTE / 01</p><h2>From perimeter<br /><em>to context.</em></h2><p>Zero Trust Architecture replaces the static network perimeter with continuous, identity-centric decisions. This working prototype maps NIST ZTA concepts to an inspectable request pipeline.</p></div><div className="research-list"><article><span>01</span><div><h3>Identity is the new perimeter</h3><p>Every request is bound to a verified user, session and MFA state rather than a trusted network location.</p></div></article><article><span>02</span><div><h3>Device posture is evidence</h3><p>Managed state, encryption, EDR health and IP reputation contribute to an explainable trust score.</p></div></article><article><span>03</span><div><h3>Least privilege is dynamic</h3><p>Policies match role and resource, then apply risk and device thresholds before granting access.</p></div></article></div></div> }

export default App